name: fa_piano
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:


  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  freezed: ^2.4.6

  dio: ^5.4.0
  
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  shared_preferences: ^2.2.2
  stack_trace: ^1.11.0

  gap: ^3.0.1

  go_router: ^14.2.0
  google_fonts: ^6.2.0

  pinput: ^3.0.1
  dropdown_button2: ^2.3.9
  flutter_svg: ^2.0.10+1

  
  
  app_tracking_transparency: ^2.0.4

  mytracker_sdk:
    git:
      url: https://github.com/RossHS/mytracker-flutter.git
      path: ./sdk

  intl: ^0.18.1

  wave: ^0.2.2

  dart_date: ^1.3.2

  collection: ^1.18.0

  dotted_border: ^2.1.0

  sliding_up_panel: ^2.0.0+1
  
  flutter_staggered_grid_view: ^0.7.0
  
  table_calendar: ^3.0.9
  
  # локальная бд
  drift: ^2.17.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.9.0
  sqlite3: ^2.4.2
  
  vibration: ^1.9.0

  flutter_slidable: ^3.1.0
  flutter_slidable_panel: ^1.1.3
  flutter_keyboard_visibility: ^6.0.0

  # firebase
  firebase_storage: ^12.0.1
  cloud_firestore: ^5.0.1
  firebase_core: ^3.0.0
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  
  # загрузка pdf
  url_launcher: ^6.3.0
  # видео плеев
  youtube_player_iframe: ^5.1.2

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.9
  drift_dev: ^2.17.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/
    - assets/app_icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 22
  