// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgZ7LSE5mBOXX85WrhVFvQntL6EM48ikI',
    appId: '1:741958141354:android:9ec1a4a364217dccc417d3',
    messagingSenderId: '741958141354',
    projectId: 'fa-piano-1',
    storageBucket: 'fa-piano-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ6D1lIHpZiqg-qXzHIy8NhZGOuzHeA4U',
    appId: '1:741958141354:ios:0a5dc2cde4d498c4c417d3',
    messagingSenderId: '741958141354',
    projectId: 'fa-piano-1',
    storageBucket: 'fa-piano-1.appspot.com',
    androidClientId: '741958141354-ctqcnff892ckuuhkpgc8i2il53796lib.apps.googleusercontent.com',
    iosClientId: '741958141354-1pvv7j3egqu5k338j4c4j13iiq9a98u2.apps.googleusercontent.com',
    iosBundleId: 'com.faPianoApp',
  );

}